### ISSUE TITLE
Greatest Webapp Idea!

### ISSUE THREAD

**Issue by keithorange** [Bloodhunter4rc/stratninja#1]
Work smart not hard eh? Have you been successful in finding profitable strategies from strat.ninja? I can see there are obviously lots of profitable strategies during backtesting, but how about in practice/dry-runs? I see you have some profitable dry-runs going :)!

**Comment by Bloodhunter4rc** [comment]
github is not for discussing the page/what strategies are profitable. the market did go up so hard to tell if anything would be profitable in the long run.

**Comment by keithorange** [comment]
ok. good luck with your attitude. I have been profitable and clearly you do not know how to backtest. Also your website continues to crash. Good lluck with php

**Comment by Bloodhunter4rc** [comment]
> ok. good luck with your attitude. I have been profitable and clearly you do not know how to backtest. Also your website continues to crash. Good lluck with php

all fine i dont get easily offended, good luck
